name: zilpay
description: "ZilPay wallet IOS, Android, Mac, Linux, Windows"
version: 3.8.26+915

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  rust_lib_zilpay:
    path: rust_builder
  flutter_rust_bridge: ^2.11.1
  path_provider: ^2.0.11
  provider: ^6.1.2
  flutter_svg: ^2.0.10+1
  local_auth: ^3.0.0
  device_info_plus: ^12.1.0
  package_info_plus: ^9.0.0
  permission_handler: ^12.0.0+1
  url_launcher: ^6.3.2
  mobile_scanner: ^7.0.1
  share_plus: ^12.0.0
  flutter_inappwebview: ^6.1.5
  file_picker: ^10.3.10
  shared_preferences: ^2.5.3
  app_links: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  integration_test:
    sdk: flutter

flutter:
  generate: true
  assets:
    - assets/icons/
    - assets/imgs/
    - assets/chains/
    - assets/zilpay_legacy_inject.js
    - assets/evm_inject.js
  fonts:
    - family: SFRounded
      fonts:
        - asset: assets/fonts/Regular.ttf    
          weight: 400                        
        - asset: assets/fonts/Bold.ttf       
          weight: 700                        
        - asset: assets/fonts/Semibold.ttf   
          weight: 600                        
        - asset: assets/fonts/Ultralight.ttf
          weight: 300    
